using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace LetItGrow.Web.Data.Common
{
    /// <summary>
    /// A record describing an error.
    /// </summary>
    public record Error
    {
        /// <summary>
        /// Initialize a new <see cref="Error"/> record.
        /// </summary>
        /// <param name="title">A title that describes the error.</param>
        /// <param name="detail">A description of the error.</param>
        /// <param name="status">An HTTP status code([RFC7231], Section 6) that describes the error.</param>
        public Error(string title, string detail, int status, IDictionary<string, string>? metadata = null)
        {
            Title = title;
            Detail = detail;
            Status = status;
            Metadata = metadata ?? new Dictionary<string, string>();
        }

        /// <summary>
        /// Initialize a new <see cref="Error"/> record.
        /// </summary>
        /// <param name="title">A title that describes the error.</param>
        /// <param name="detail">A description of the error.</param>
        /// <param name="status">An HTTP status code([RFC7231], Section 6) that describes the error.</param>
        public Error(string title, string detail, int status, Dictionary<string, string> metadata)
            : this(title, detail, status, metadata as IDictionary<string, string>)
        {
        }

        /// <summary>
        /// The name (code) of the error.
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; init; }

        /// <summary>
        /// The message that describes the error.
        /// </summary>
        [JsonPropertyName("detail")]
        public string Detail { get; init; }

        /// <summary>
        /// The HTTP status code([RFC7231], Section 6) generated by the origin server for
        /// this occurrence of the problem.
        /// </summary>
        [JsonPropertyName("status")]
        public int Status { get; init; }

        /// <summary>
        /// An object to include extra data for the client.
        /// This is not a required field.
        /// </summary>
        [JsonPropertyName("metadata")]
        public IDictionary<string, string> Metadata { get; init; }
    }
}