Urls: https://*:6001

Application: 
  Name: Identity
  Version: 1

Swagger: 
  Enabled: false

Services:
  Blazor: <The full Blazor application url>

Databases:
  Connection: <Postgres db connection string here>
  Schema: letitgrow_identity

Secrets:
  JWT: <JWT Secret here>

Serilog:
  MinimumLevel:
    Default: Information
    Override:
      System: Warning
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
  WriteTo:
    - { Name: Console }
    - { Name: File, Args: { Path: "logs/logs.txt", RollingInterval: Day } }
  Enrich:
    - FromLogContext
  Properties:
    Application: Identity

#Kestrel:
#  EndpointDefaults: { Protocols: Http2 }

AllowedHosts: "*"