Urls: http://localhost:6000;https://localhost:6001

Swagger: 
  Enabled: true

Services:
  Blazor: https://localhost:5001

Databases:
  Connection: Host=localhost;Database=postgres;Username=admin;Password=password
  Schema: letitgrow_identity

Secrets:
  JWT: DRjd/GnduI3Efzen9V9BvbNUfc/VKgXltV7Kbk9sMkY=