Urls: https://*:5021

Swagger: 
  Enabled: false

Services:
  Blazor: <The full Blazor application url>
  CouchDb: <The couchdb username;password;url;db example => admin;admin;http://localhost:5984;my_database (db is optional)>

Secrets:
  JWT: <JWT Secret here>

Serilog:
  MinimumLevel:
    Default: Information
    Override:
      System: Warning
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
  WriteTo:
    - { Name: Console }
    - { Name: File, Args: { Path: "logs/logs.txt", RollingInterval: Day } }

AllowedHosts: "*"
